-- AutoMarkAssist_DB_Classic.lua
-- Mob mark-preference database for Classic (Vanilla) dungeons and raids.
-- This is the first DB module loaded. It defines the legacy Classic table and
-- merges its entries into the runtime lookup without clobbering existing rows.
-- Subsequent expansion modules merge into the runtime table.
--
-- NOTE: Mob names reflect post-Cataclysm revamps where applicable.
-- Classic Era and TBC/WotLK Classic servers may use original pre-Cata names
-- for some mobs.  Unknown mobs are marked via FCFS; adjust entries
-- in-game via the Database tab or by editing this file directly.
--
-- Mark values:
--   8        -> Skull (priority kill target)
--   5        -> Moon  (CC preference, e.g. Polymorph)
--   1-7      -> Any specific mark preference
--   "SKIP"   -> Never mark this mob.
--
-- Context-dependent tactics may be note-only. Such rows have no default mark,
-- creature type, CC flag, or danger level and cannot alter automatic scoring.
-- Adjust via the in-game Database tab or by editing this file directly.

-- Creates the global database tables that subsequent expansion modules merge into.

AutoMarkAssist_MobDB = {

    -- ============================================================
    -- CLASSIC DUNGEONS
    -- ============================================================

    ["Ragefire Chasm"] = {
        ["Searing Blade Cultist"]       = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Curses and casts at range; CC or kill after the Warlock." },
        ["Searing Blade Enforcer"]      = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Searing Blade Warlock"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow caster that opens with Immolate and Shadow Bolt; interrupt and kill it before the melee reach the tank." },
        ["Corrupted Houndmaster"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Calls beasts to the pull; kill it early or the pack keeps growing." },
        ["Dark Shaman Acolyte"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Flame Shock caster and healer for the trogg packs; interrupt and focus first." },
        ["Molten Elemental"]            = { mark = 4, creatureType = "Elemental", dangerLevel = 2, note = "Warlock Banish target; otherwise kill it away from the melee." },
        ["Ragefire Shaman"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Lightning caster; kill after the Acolyte." },
        ["Ragefire Trogg"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
    },

    ["Wailing Caverns"] = {
        ["Druid of the Fang"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "The dangerous trash here: casts Healing Touch and Druid's Slumber. Interrupt the heal, dispel or Tremor the sleep." },
        ["Deviate Viper"]               = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Deviate Adder"]               = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Deviate Raptor"]              = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Deviate Ravager"]             = { mark = 5, creatureType = "Beast", dangerLevel = 2, note = "Hard melee; kill it before the smaller beasts." },
        ["Deviate Shambler"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Deviate Stinglash"]           = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Serpentbloom Snake"]          = "SKIP",
        ["Deviate Moccasin"]            = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
    },

    ["The Deadmines"] = {
        ["Defias Blood Wizard"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Haste-buffs and drops a shared-damage field; kill or CC it early." },
        ["Defias Squallshaper"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Defias Envoker"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Alternate spelling of the elite caster; treat as a first-kill target." },
        ["Defias Pirate"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Taskmaster"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Opens with Piercing Shot from range to strip the tank's armor; kill or CC it first." },
        ["Defias Overseer"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Elite that walks with non-elite miners, so pulls are bigger than they look." },
        ["Defias Evoker"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Elite Fireball caster; kill it before the melee." },
        ["Defias Cannoneer"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Ranged burst on the ship deck." },
        ["Defias Watcher"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Strip Miner"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Pierce Armor in melee." },
        ["Goblin Woodcarver"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Goblin Engineer"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Throws bombs; CC or kill after the casters." },
        ["Goblin Shipbuilder"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Miner"]                = { mark = 5, creatureType = "Humanoid", dangerLevel = 1, note = "Flees at low health and brings friends; keep a snare or stun ready." },
    },

    ["Shadowfang Keep"] = {
        ["Tormented Officer"]           = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Wailing Guardsman"]           = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Casts a 5-second AoE silence (not a fear); kill or control before it silences the healer and casters." },
        ["Unstable Ravager"]            = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Shadowfang Darksoul"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill first." },
        ["Shadowfang Glutton"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowfang Moonwalker"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Casts Healing Touch; interrupt and kill first." },
        ["Shadowfang Ragetooth"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowfang Whitescalp"]       = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowfang Wolfguard"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Dark Creeper"]                = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Corpse Eater"]                = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Bleak Worg"]                  = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Slavering Worg"]              = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Lupine Horror"]               = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Lupine Delusion"]             = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Fel Steed"]                   = { note = "Hits hard but can be skipped; avoid an unnecessary pull." },
        ["Vile Bat"]                    = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
    },

    ["The Stockade"] = {
        ["Defias Captive"]              = { mark = 7, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Prisoner"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Insurgent"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Convict"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Inmate"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Defias Wizard"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster that locks a player out and slows; interrupt and kill first." },
        ["Riverpaw Mystic"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and buffs the gnoll packs; kill before the Brutes." },
        ["Riverpaw Overseer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Heavy hitter; kill after the casters." },
        ["Riverpaw Herbalist"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt its casts." },
        ["Riverpaw Brute"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
    },

    ["Blackfathom Deeps"] = {
        ["Twilight Aquamancer"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Calls an Aqua Guardian, adding a mob to the pull; kill it early." },
        ["Twilight Shadowmage"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Dominate Minds a player and summons a Voidwalker; kill or CC it before anything else." },
        ["Twilight Loreseeker"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Enlarges itself for more damage." },
        ["Twilight Acolyte"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Twilight healer; CC it or kill it first in every cultist pack." },
        ["Twilight Thug"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Blackfathom Tide Priestess"]  = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Murkshallow Snapclaw"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 1, note = "Disarms the tank; kill after the casters." },
        ["Fallenroot Rogue"]            = { mark = 3, creatureType = "Humanoid", dangerLevel = 2, note = "Rogue Sap target." },
        ["Fallenroot Shaman"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and drops totems; interrupt and kill first." },
        ["Fallenroot Satyr"]            = { mark = 5, creatureType = "Demon", dangerLevel = 2 },
        ["Barbed Crustacean"]           = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Aku'mai Servant"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Aku'mai Snapjaw"]             = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Blindlight Oracle"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals, shields itself and Fears; kill or interrupt it before anything else in the murloc room." },
        ["Blindlight Muck Dweller"]       = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Applies Leech Poison to the tank." },
        ["Blackfathom Oracle"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healing Wave plus a poison DoT; interrupt and kill first." },
        ["Blackfathom Sea Witch"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Blizzard and Frost Nova; kill it before the melee close in." },
        ["Twilight Elementalist"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Chain shocks; interrupt and kill first." },
        ["Twilight Reaver"]               = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, note = "Arcing Smash hits the whole melee group." },
    },

    ["Gnomeregan"] = {
        ["Arcane Nullifier X-21"]       = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, ccImmune = true },
        ["Leprous Technician"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Supercharges and repairs the machines around it; kill the gnome before the constructs." },
        ["Leprous Machinesmith"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Supercharges and repairs the machines around it; kill the gnome before the constructs." },
        ["Leprous Gnome"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Leprous Assistant"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Caverndeep Burrower"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Caverndeep Ambusher"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Caverndeep Looter"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Caverndeep Trapper"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Mobile Alert System"]         = { mark = 8, creatureType = "Mechanical", dangerLevel = 3, note = "Alarm bot; kill it first or it calls the next pack. Mechanical, so Sap and Polymorph do not work.", ccImmune = true },
        ["Dark Iron Agent"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Dark Iron Ambassador"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Fireball caster; interrupt on sight." },
        ["Crowd Pummeler 9-60"]         = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, ccImmune = true },
        ["Peacekeeper Security Suit"]   = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, ccImmune = true },
        ["Alarm-a-bomb 2600"]           = { mark = 8, creatureType = "Mechanical", dangerLevel = 3, note = "Explodes on contact; kill it at range before it reaches the group.", ccImmune = true },
        ["Security Golem"]              = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, ccImmune = true },
        ["Walking Bomb"]                = "SKIP",
        ["Irradiated Horror"]             = { mark = 8, creatureType = "Aberration", dangerLevel = 3, note = "Chain Burn jumps to three players and burns mana; kill or interrupt it first." },
        ["Corrosive Lurker"]              = { mark = 7, creatureType = "Aberration", dangerLevel = 2, note = "Stacks Corrosive Ooze on the tank." },
        ["Irradiated Slime"]              = { mark = 5, creatureType = "Aberration", dangerLevel = 2, note = "Leaves a Radiation Cloud on the ground." },
        ["Leprous Defender"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Mechano-Frostwalker"]           = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, note = "Ice Blast freezes everyone nearby; mechanical, so Sap and Polymorph do not work." },
        ["Mechano-Flamewalker"]           = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, note = "Flame Spray and Fire Nova; keep casters at range." },
        ["Mechanized Sentry"]             = { mark = 7, creatureType = "Mechanical", dangerLevel = 2, note = "Alarm bot; kill it before it calls the next pack." },
        ["Mechanized Guardian"]           = { mark = 7, creatureType = "Mechanical", dangerLevel = 2 },
    },

    ["Razorfen Kraul"] = {
        ["Razorfen Dustweaver"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Razorfen Geomancer"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Razorfen Warden"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Razorfen Defender"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Razorfen Battleguard"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Death's Head Seer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Shadow caster." },
        ["Death's Head Cultist"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Death's Head Adept"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill before the melee." },
        ["Razorfen Servitor"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Razorfen Beastmaster"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Razorfen Handler"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Commands the beasts in the pack; kill it early." },
        ["Greater Kraul Bat"]           = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Kraul Bat"]                   = "SKIP",
        ["Agile Kraul"]                 = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
    },

    ["Razorfen Downs"] = {
        ["Ragglesnout"]                = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Rare priest-type mob can Dominate Mind and heal; interrupt the heal and control the mind-control cast." },
        ["Death's Head Necromancer"]    = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },  -- raises undead
        ["Death's Head Sage"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Death's Head Priest"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Death's Head Ward Keeper"]    = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster and healer; interrupt and kill first." },
        ["Withered Quilguard"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Withered Battle Boar"]        = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Withered Reaver"]             = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Withered Spearhide"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Frozen Soul"]                 = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Plaguemaw the Rotting"]       = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Tomb Fiend"]                  = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Tomb Reaver"]                 = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
    },

    ["Scarlet Halls"] = {
        ["Scarlet Evoker"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill first." },
        ["Scarlet Treasurer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },  -- healer
        ["Scarlet Scholar"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals the pack; interrupt and kill first." },
        ["Scarlet Cannoneer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Master Dog Trainer"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },  -- beast caller
        ["Scarlet Evangelist"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster; kill after the Scholar." },
        ["Scarlet Myrmidon"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Enrages at low health." },
        ["Scarlet Defender"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Hound"]                       = "SKIP",
    },

    ["Scarlet Monastery"] = {
        ["Scarlet Zealot"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Scarlet Chaplain"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Priest that shields and renews the pack; kill it quickly." },
        ["Scarlet Judicator"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Scarlet Fanatic"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Scarlet Friar"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Scarlet Purifier"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and cleanses; kill before the melee." },
        ["Scarlet Centurion"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Battle Shout buff for the pack." },
        ["Scarlet Torturer"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Scarlet Interrogator"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Scarlet Wizard"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Instant Arcane Explosion plus Fire Shield; kill it fast and do not stack on it." },
        ["Scarlet Abbot"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Casts Renew and Heal; must be interrupted and killed fast." },
        ["Scarlet Monk"]                = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "High melee damage, low armor." },
        ["Scarlet Sorcerer"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; kill before the melee reach the tank." },
    },

    ["Zul'Farrak"] = {
        ["Sandfury Witch Doctor"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and drops totems; interrupt and kill first." },
        ["Sandfury Shadowcaster"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow Bolt Volley caster; interrupt and kill first." },
        ["Sandfury Firecaller"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Fire caster; interrupt and kill first." },
        ["Sandfury Blood Drinker"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Self-heals with an AoE component; CC or stun it and focus it down." },
        ["Sandfury Zealot"]             = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, note = "Guards Theka; Sap, Polymorph or Fear them, or gather them on the tank before committing to the boss." },
        ["Sandfury Axe Thrower"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Ranged; disarmable, and a common primary sheep target." },
        ["Sandfury Drudge"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Sandfury Guardian"]           = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Sandfury Hideskinner"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Sandfury Soul Eater"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Life-drain caster; kill it before the melee." },
        ["Sandfury Executioner"]        = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, note = "Heavy melee at the top of the temple steps." },
        ["Sul'lithuz Warder"]           = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Sul'lithuz Broodling"]        = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Troll Totem"]                 = "SKIP",
    },

    ["Maraudon"] = {
        ["Celebras Elementalist"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Elemental caster; interrupt and kill first." },
        ["Barbed Lasher"]               = { mark = 5, creatureType = "Elemental", dangerLevel = 1 },
        ["Putrid Shrieker"]             = { mark = 8, creatureType = "Demon", dangerLevel = 3, note = "Satyr caster; kill or CC it first." },
        ["Vile Larva"]                  = "SKIP",
        ["Centaur Pariah"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Maraudine Bonepaw"]           = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Maraudine Stormer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Chain Lightning caster; interrupt and kill first." },
        ["Maraudine Scout"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Maraudine Khan Advisor"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and buffs the centaur packs; interrupt and kill first." },
        ["Maraudine Wrangler"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Handles the beasts in the pack; kill it early." },
        ["Meshlok the Harvester"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Theradrim Guardian"]          = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Theradrim Shardling"]         = { mark = 5, creatureType = "Elemental", dangerLevel = 1 },
        ["Thessala Hydra"]              = { mark = 8, creatureType = "Beast", dangerLevel = 2, ccImmune = true },
        ["Noxxion's Spawn"]             = "SKIP",
        ["Poison Sprite"]               = { mark = 5, creatureType = "Elemental", dangerLevel = 2 },
        ["Spewed Larva"]                = "SKIP",
        ["Putridus Shadowstalker"]        = { mark = 8, creatureType = "Demon", dangerLevel = 3, note = "Stealths and backstabs from behind; kill it early and watch for the shimmer." },
        ["Putridus Trickster"]            = { mark = 7, creatureType = "Demon", dangerLevel = 2 },
        ["Cavern Shambler"]               = { mark = 7, creatureType = "Humanoid", dangerLevel = 3, note = "Self-heals with Wild Regeneration; interrupt the heal." },
        ["Cavern Lurker"]                 = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, note = "Knocks the tank down." },
        ["Noxious Slime"]                 = { mark = 5, creatureType = "Aberration", dangerLevel = 2, note = "Noxious Cloud hurts everyone near it; pull one at a time." },
        ["Creeping Sludge"]               = { mark = 5, creatureType = "Aberration", dangerLevel = 2, note = "Noxious Cloud hurts everyone near it; pull one at a time." },
    },

    ["Dire Maul"] = {
        ["Gordok Ogre-Mage"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Flamestrike, Frostbolt and Polymorph; kill it first." },
        ["Gordok Warlock"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Summons demons into the pull; kill or CC it immediately." },
        ["Gordok Mage-Lord"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Flamestrike, Frostbolt and Polymorph; kill it first." },
        ["Gordok Bushwacker"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Gordok Brute"]                = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gordok Enforcer"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gordok Reaver"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gordok Mastiff"]              = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Gordok Captain"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gordok Mauler"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Wildspawn Imp"]               = { mark = 4, creatureType = "Demon", dangerLevel = 1, note = "Warlock Banish target." },
        ["Wildspawn Shadowstalker"]     = { mark = 8, creatureType = "Demon", dangerLevel = 3, note = "Stealthed backstabber; kill it early so it cannot open on the healer." },
        ["Wildspawn Felsworn"]          = { mark = 8, creatureType = "Demon", dangerLevel = 3, note = "Casts Fear plus Shadow Bolt and Shadow Shield; kill or CC it first." },
        ["Wildspawn Rogue"]             = { mark = 3, creatureType = "Demon", dangerLevel = 2, note = "Rogue Sap target." },
        ["Wildspawn Satyr"]             = { mark = 7, creatureType = "Demon", dangerLevel = 2 },
        ["Wildspawn Betrayer"]          = { mark = 7, creatureType = "Demon", dangerLevel = 2, note = "Exploding Shot and Shadow Shot from range." },
        ["Warpwood Treant"]             = { mark = 5, creatureType = "Elemental", dangerLevel = 2 },
        ["Warpwood Stomper"]            = { mark = 7, creatureType = "Elemental", dangerLevel = 2, note = "War Stomps the melee group; interrupt the stomp chain." },
        ["Warpwood Guardian"]           = { mark = 7, creatureType = "Elemental", dangerLevel = 3, note = "Heals the other ancients with Regrowth; interrupt the heal and kill it first." },
        ["Warpwood Moss Flayer"]        = { mark = 5, creatureType = "Elemental", dangerLevel = 1 },
        ["Warpwood Shredder"]           = { mark = 5, creatureType = "Elemental", dangerLevel = 2 },
        ["Felvine Shard"]               = "SKIP",
        ["Lethtendris"]                 = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hydrospawn"]                  = { mark = 8, creatureType = "Elemental", dangerLevel = 2 },
        ["Mushgog"]                     = { mark = 8, creatureType = "Elemental", dangerLevel = 2 },
        ["Isalien"]                     = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Zevrim Thornhoof"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Wildspawn Hellcaller"]          = { mark = 8, creatureType = "Demon", dangerLevel = 3, note = "Rain of Fire and Fireball Volley; interrupt or CC it first and step out of the fire." },
        ["Wildspawn Trickster"]           = { mark = 7, creatureType = "Demon", dangerLevel = 2, note = "Curse of Weakness on the group." },
        ["Warpwood Crusher"]              = { mark = 7, creatureType = "Elemental", dangerLevel = 2, note = "Tramples and Crush Armors the tank." },
        ["Warpwood Tangler"]              = { mark = 7, creatureType = "Elemental", dangerLevel = 2, note = "Entangling Roots plus Lightning Bolt." },
        ["Mana Remnant"]                  = { mark = 5, creatureType = "Elemental", dangerLevel = 2, note = "Guards a pylon; clear them so Immol'thar becomes attackable." },
        ["Magister Kalendris"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow priest with Mind Flay, Mind Blast and Mind Control; kill or CC him first." },
    },

    ["Stratholme"] = {
        ["Risen Sorcerer"]              = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Caster; kill before the melee." },
        ["Risen Priest"]                = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Healer; interrupt or Shackle Undead it." },
        ["Risen Lackey"]                = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Risen Bonewarder"]            = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Risen Warlord"]               = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Risen Guard"]                 = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Risen Constable"]             = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Risen Hammersmith"]           = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Risen Deathsworn"]            = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Crimson Sorcerer"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Polymorphs a player and casts Arcane Explosion; kill or CC it early." },
        ["Crimson Priest"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt every Heal or sheep it and kill it last." },
        ["Crimson Gallant"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Crimson Inquisitor"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Crimson Conjurer"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Summons elemental pets; kill it first or sheep it and save it for last." },
        ["Crimson Initiate"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Crimson Defender"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1, note = "Stuns but is not a major threat." },
        ["Crimson Battle Mage"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heavy Arcane Explosion; a priority kill unless you sheep it." },
        ["Crimson Monk"]                = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Thuzadin Necromancer"]        = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Raises undead into the pull; kill or CC it first." },
        ["Thuzadin Shadowcaster"]       = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Shadow caster; interrupt and kill first." },
        ["Thuzadin Acolyte"]            = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Eye of Naxxramas"]            = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Ash'ari Crystal"]             = "SKIP",
        ["Skeletal Sorcerer"]           = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Caster; kill before the melee skeletons." },
        ["Skeletal Guardian"]           = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Skeletal Berserker"]          = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Mindless Skeleton"]           = "SKIP",
        ["Mindless Zombie"]             = "SKIP",
        ["Plagued Rat"]                 = "SKIP",
        ["Plagued Maggot"]              = "SKIP",
        ["Plagued Gargoyle"]            = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Plagued Ghoul"]               = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Patchwork Horror"]            = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Ghostly Citizen"]             = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Spectral Citizen"]            = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Cannibal Ghoul"]              = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Crypt Crawler"]               = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Crypt Beast"]                 = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Crypt Slayer"]                = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Crypt Fiend"]                 = { mark = 8, creatureType = "Undead", dangerLevel = 2, note = "Web wraps and burrows; kill it before it escapes." },
        ["Venom Belcher"]               = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Crimson Sorceress"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Undead Scarab"]                 = { mark = 5, creatureType = "Beast", dangerLevel = 1, note = "Casts Net, a root plus silence; do not let it silence the healer." },
        ["Malor the Zealous"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Lay on Hands back to full health; burn him down through it." },
    },

    ["Scholomance"] = {
        ["Scholomance Acolyte"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster packs are dangerous; pull one group at a time back toward the entrance to avoid chain pulls." },
        ["Scholomance Necrolyte"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "High-risk caster; isolate its pack and interrupt dangerous casts." },
        ["Scholomance Neophyte"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Scholomance Student"]         = { note = "Viewing-room elite students are commonly skipped unless needed for a quest." },
        ["Scholomance Adept"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster-pack target; use careful single-pack pulls and interrupt casts where possible." },
        ["Scholomance Dark Summoner"]   = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Scholomance Occultist"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster-pack target; avoid chaining nearby pulls." },
        ["Boneweaver"]                  = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Raises skeletons into the pull; kill or CC it first." },
        ["Candlestick Mage"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster; pull carefully with nearby Scholomance packs." },
        ["Reanimated Corpse"]           = "SKIP",
        ["Risen Construct"]             = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Risen Abomination"]           = { mark = 5, creatureType = "Undead", dangerLevel = 2 },
        ["Risen Protector"]             = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Risen Guardsman"]             = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Unstable Corpse"]             = { mark = 5, creatureType = "Undead", dangerLevel = 2, note = "Explodes on death; kill it away from the group." },
        ["Wailing Death"]               = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Diseased Ghoul"]              = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Rattlegore"]                  = { mark = 8, creatureType = "Undead", dangerLevel = 2, note = "The nearby trash hits hard and can stun tanks; pull the room slowly and separately." },
    },

    ["The Temple of Atal'Hakkar"] = {
        ["Atal'ai Deathwalker"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; clear these before engaging Jammal'an." },
        ["Atal'ai Priest"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Atal'ai Witch Doctor"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and drops totems; interrupt and kill first." },
        ["Atal'ai Slave"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Atal'ai Warrior"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Atal'ai High Priest"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer and caster; the first kill in every troll pack." },
        ["Gaseous Lurker"]              = { mark = 4, creatureType = "Elemental", dangerLevel = 2, note = "Warlock Banish target." },
        ["Suppressor"]                  = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Murk Spawn"]                  = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Temple Interior Guardian"]    = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hakkari Bloodkeeper"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hakkari Frostwing"]           = { mark = 5, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Hakkari Minion"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Hakkari Oracle"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill first." },
        ["Hakkari Shadowcaster"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow caster; interrupt and kill first." },
        ["Jade Ooze"]                   = "SKIP",
        ["Jade Sludge"]                 = "SKIP",
        ["Spawn of Hakkar"]             = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
    },

    ["Blackrock Depths"] = {
        ["Shadowforge Surveyor"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowforge Flame Keeper"]    = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowforge Sharpshooter"]    = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowforge Senator"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowforge Citizen"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Shadowforge Warder"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Shadowforge Darkweaver"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill first." },
        ["Shadowforge Darkcaster"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow Bolt Volley and Mana Burn; interrupt and kill first." },
        ["Shadowforge Peasant"]         = "SKIP",
        ["Shadowforge Chanter"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and buffs; interrupt and kill first." },
        ["Dark Iron Medic"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Dark Iron Tastetester"]       = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Dark Iron Slaver"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Dark Iron Lookout"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Dark Iron Raider"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Dark Iron Watchman"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Dark Iron Steamsmith"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Anvilrage Officer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Chains and controls a player; kill or CC it first." },
        ["Anvilrage Guardsman"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Anvilrage Warden"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Anvilrage Soldier"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Anvilrage Footman"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Anvilrage Marshal"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill first." },
        ["Anvilrage Medic"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Anvilrage Reservist"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Ragereaver Golem"]            = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, note = "Immune to humanoid CC." },
        ["Wrath Hammer Construct"]      = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, note = "Immune to humanoid CC." },
        ["Molten War Golem"]            = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, note = "Immune to humanoid CC; tank it separately." },
        ["Core Rager"]                  = { mark = 8, creatureType = "Elemental", dangerLevel = 2, note = "Warlock Banish target." },
        ["Bael'Gar"]                    = { mark = 8, creatureType = "Elemental", dangerLevel = 2 },
        ["Fireguard"]                   = { mark = 5, creatureType = "Elemental", dangerLevel = 2, note = "Warlock Banish target." },
        ["Twilight's Hammer Torturer"]  = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Twilight's Hammer Ambassador"] = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Cult caster; interrupt and kill first." },
        ["Weapon Technician"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Ironhand Guardian"]           = { mark = 8, creatureType = "Mechanical", dangerLevel = 2, note = "Immune to humanoid CC.", ccImmune = true },
    },

    ["Lower Blackrock Spire"] = {
        ["Blackhand Summoner"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Summons into the pull; kill or CC it first." },
        ["Blackhand Incarcerator"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Immobilises a player." },
        ["Blackhand Dragon Handler"]    = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Blackhand Iron Guard"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Blackhand Veteran"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Blackhand Assassin"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Opens from stealth; kill it early." },
        ["Smolderthorn Shadow Priest"]  = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Smolderthorn Witch Doctor"]   = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and drops totems; interrupt and kill first." },
        ["Smolderthorn Seer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Smolderthorn Headhunter"]     = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Smolderthorn Berserker"]      = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Smolderthorn Axe Thrower"]    = { mark = 6, creatureType = "Humanoid", dangerLevel = 2, note = "Hunter Freezing Trap target." },
        ["Smolderthorn Mystic"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Scarshield Warlock"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Opens a portal and demons keep coming through; kill or CC it immediately or the pull snowballs." },
        ["Scarshield Spellbinder"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heavy Arcane Missiles; kill it first or mind-control it." },
        ["Scarshield Quartermaster"]    = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Scarshield Legionnaire"]      = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Spirestone Mystic"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Spirestone Ogre Magus"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Arcane bolt volley; always a kill priority." },
        ["Spirestone Battle Mage"]      = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Spirestone Lord Magus"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; kill first." },
        ["Spirestone Warlord"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Spirestone Butcher"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Spirestone Enforcer"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Rage Talon Dragonspawn"]      = { mark = 5, creatureType = "Dragonkin", dangerLevel = 1 },
        ["Rage Talon Flamescale"]       = { mark = 5, creatureType = "Dragonkin", dangerLevel = 1 },
        ["Rage Talon Fire Tongue"]      = { mark = 7, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Rage Talon Captain"]          = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Firebrand Grunt"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Heavy melee." },
        ["Firebrand Legionnaire"]       = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["War Hound"]                   = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Shadowforge Spirit"]          = { mark = 5, creatureType = "Undead", dangerLevel = 1 },
        ["Spire Spider"]                  = { mark = 8, creatureType = "Beast", dangerLevel = 3, note = "Magic stun that drops threat, and spawns spiderlings on death; first priority in the spider packs." },
        ["Spire Spiderling"]              = { mark = 5, creatureType = "Beast", dangerLevel = 1, note = "AoE them once the tank has threat, after both Spire Spiders are dead." },
        ["Urok Ogre Magus"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Arcane bolt volley; always a kill priority." },
        ["Urok Enforcer"]                 = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Blackrock Summoner"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Summons players to a random spot, including the pit edges; kill it on priority and do not move when pulled." },
    },

    ["Uldaman"] = {
        ["Shadowforge Geologist"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Flame Spike on the ground and a Shield Bash that locks a caster out." },
        ["Shadowforge Darkcaster"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow Bolt Volley and Mana Burn; interrupt the volley and kill first." },
        ["Shadowforge Relic Hunter"]    = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Silences and heals; CC it or kill it first." },
        ["Shadowforge Archaeologist"]   = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Shadowforge Ruffian"]         = { mark = 3, creatureType = "Humanoid", dangerLevel = 1, note = "Rogue Sap target." },
        ["Shadowforge Shovelphlange"]   = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Shadowforge Ambusher"]        = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Shadowforge Sharpshooter"]    = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, note = "Ranged shooter; kill after the casters." },
        ["Stonevault Pillager"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Stonevault Brawler"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Stonevault Geomancer"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Fireball and Flame Buffet; interrupt and kill first." },
        ["Stonevault Oracle"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Stonevault Flameweaver"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Fire caster; interrupt and kill first." },
        ["Stonevault Ambusher"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Stonevault Mauler"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Earthen Custodian"]           = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, ccImmune = true },
        ["Earthen Guardian"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Earthen Sculptor"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Earthen Hallshaper"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Stone Steward"]               = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, ccImmune = true },
        ["Jadespine Basilisk"]          = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Cleft Scorpid"]               = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Shrieking Bat"]               = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Venomlash Scorpid"]           = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
    },

    ["Upper Blackrock Spire"] = {
        ["Blackhand Summoner"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Summons into the pull; kill or CC it first." },
        ["Blackhand Dreadweaver"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow caster; interrupt and kill first." },
        ["Blackhand Incarcerator"]      = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Blackhand Dragon Handler"]    = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Blackhand Veteran"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Blackhand Iron Guard"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Blackhand Assassin"]          = { mark = 3, creatureType = "Humanoid", dangerLevel = 2 },
        ["Blackhand Thug"]              = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Rage Talon Fire Tongue"]      = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Rage Talon Captain"]          = { mark = 7, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Rage Talon Dragon Guard"]     = { mark = 5, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Rage Talon Flamescale"]       = { mark = 5, creatureType = "Dragonkin", dangerLevel = 1 },
        ["Chromadrake"]                 = { mark = 2, creatureType = "Dragonkin", dangerLevel = 2, note = "Druid Hibernate target." },
        ["Rookery Whelp"]               = "SKIP",
        ["Rookery Guardian"]            = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2 },
    },

    -- ============================================================
    -- CLASSIC RAIDS
    -- ============================================================

    ["Molten Core"] = {
        ["Firelord"]                    = { mark = 8, creatureType = "Elemental", dangerLevel = 2, note = "Kill the Lava Spawn adds as they appear; these are not Ragnaros' Sons of Flame." },
        ["Flamewaker"]                  = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster; interrupt after the Elite." },
        ["Flamewaker Elite"]            = { note = "Majordomo pack: keep the elites controlled/tanked separately and follow the raid-assigned add order." },
        ["Flamewaker Healer"]           = { mark = 8, creatureType = "Elemental", dangerLevel = 3 },
        ["Flamewaker Priest"]           = { mark = 8, creatureType = "Elemental", dangerLevel = 3 },
        ["Flamewaker Protector"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Firesworn"]                   = { note = "Explodes on death; spread and handle one at a time. Its relative kill order depends on the raid plan, so no fixed mark is enforced." },
        ["Son of Flame"]                = { mark = 8, creatureType = "Elemental", dangerLevel = 3, note = "Ragnaros phase add; control and burn promptly according to the raid assignment." },
        ["Ancient Core Hound"]          = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Core Hound"]                  = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Lava Elemental"]              = { mark = 4, creatureType = "Elemental", dangerLevel = 2, note = "Elemental trash can be banished or stunned; coordinate control with the tank." },
        ["Lava Surger"]                 = { mark = 4, creatureType = "Elemental", dangerLevel = 2, note = "Knockback hazard; fight away from ledges and use Banish/other control if assigned." },
        ["Lava Annihilator"]            = { note = "Handle as a separate tanked elemental; exact focus order is pack-dependent." },
        ["Lava Reaver"]                 = { mark = 4, creatureType = "Elemental", dangerLevel = 2, note = "May be banished/controlled; follow the tank and raid assignment." },
        ["Primal Flame Elemental"]      = { mark = 4, creatureType = "Elemental", dangerLevel = 2, note = "Warlock Banish target." },
        ["Molten Giant"]                = { note = "Stuns and heavy melee make separate tanking important; giants are handled one at a time, not by a universal kill order." },
        ["Molten Destroyer"]            = { note = "Stuns and heavy melee make separate tanking important; giants are handled one at a time, not by a universal kill order." },
        ["Flame Imp"]                   = "SKIP",
        ["Lava Spawn"]                  = { mark = 8, creatureType = "Elemental", dangerLevel = 3, note = "Firelord adds; switch to and kill these promptly as they spawn." },
    },

    ["Onyxia's Lair"] = {
        ["Onyxian Warder"]              = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Onyxian Whelp"]                = "SKIP",
        ["Onyxian Lair Guard"]          = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2 },
    },

    ["Blackwing Lair"] = {
        ["Grethok the Controller"]     = { mark = 8, creatureType = "Humanoid", dangerLevel = 3 },
        ["Blackwing Mage"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster priority on later mixed pulls; kill casters while tanks hold the dangerous dragonkin separately." },
        ["Blackwing Spellbinder"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 2, note = "Caster priority on later mixed pulls; keep the tanked dragonkin controlled separately." },
        ["Blackwing Taskmaster"]        = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Blackwing Warlock"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Focus dangerous caster adds while tanks hold Overseers/Wyrmguards separately." },
        ["Blackwing Guardsman"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Blackwing Legionnaire"]       = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Blackwing Technician"]        = { mark = "SKIP", creatureType = "Humanoid", note = "Hunter kites these bomb-throwers; the raid ignores them while killing the other adds. Do not focus-mark." },
        ["Death Talon Captain"]         = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2, note = "Demoralises the raid; kill after the Wyrmguards." },
        ["Death Talon Flamescale"]      = { mark = 5, creatureType = "Dragonkin", dangerLevel = 1 },
        ["Death Talon Hatcher"]         = { mark = 8, creatureType = "Dragonkin", dangerLevel = 3 },
        ["Death Talon Overseer"]        = { note = "Very dangerous; tank separately and space from Wyrmguards while the raid kills casters. The encounter plan, not a fixed mark, controls its order." },
        ["Death Talon Seether"]         = { mark = 8, creatureType = "Dragonkin", dangerLevel = 2 },
        ["Death Talon Dragonspawn"]     = { mark = 5, creatureType = "Dragonkin", dangerLevel = 1 },
        ["Death Talon Wyrmkin"]         = { mark = 5, creatureType = "Dragonkin", dangerLevel = 1 },
        ["Death Talon Wyrmguard"]       = { note = "Very dangerous; tank separately and space from Overseers while the raid kills casters. The encounter plan, not a fixed mark, controls its order." },
        ["Master Elemental Shaper Krixix"] = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Enraged Felguard"]            = { mark = 5, creatureType = "Demon", dangerLevel = 2, note = "Warlock Banish target." },
        ["Black Whelp"]                 = "SKIP",
        ["Blue Whelp"]                  = "SKIP",
        ["Bronze Whelp"]                = "SKIP",
        ["Corrupted Blue Whelp"]        = "SKIP",
        ["Corrupted Bronze Whelp"]      = "SKIP",
        ["Corrupted Green Whelp"]       = "SKIP",
        ["Corrupted Red Whelp"]         = "SKIP",
        ["Green Whelp"]                 = "SKIP",
        ["Red Whelp"]                   = "SKIP",
    },

    ["Zul'Gurub"] = {
        ["Gurubashi Bat Rider"]         = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gurubashi Blood Drinker"]     = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Self-heals with an AoE component; sheep or stun it and focus it down." },
        ["Gurubashi Berserker"]         = { mark = 5, creatureType = "Humanoid", dangerLevel = 2, note = "Enrages at low health." },
        ["Gurubashi Headhunter"]        = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gurubashi Axe Thrower"]       = { mark = 6, creatureType = "Humanoid", dangerLevel = 2, note = "Ranged; a common primary trap target, and disarmable." },
        ["Gurubashi Champion"]          = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Gurubashi Warrior"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Hakkari Blood Priest"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Nukes and heals; kill it first, or CC it if the group has no reliable interrupt." },
        ["Hakkari Priest"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; the first kill in every troll pack." },
        ["Hakkari Shadow Hunter"]       = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hakkari Shadowcaster"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Shadow caster; interrupt and kill first." },
        ["Hakkari Witch Doctor"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Heals and drops totems; kill it before the melee." },
        ["Mad Servant"]                 = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Ohgan"]                       = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Powerful Healing Ward"]       = { mark = 8, creatureType = "Totem", dangerLevel = 3, note = "Totem that heals the whole pack; destroy it immediately." },
        ["Son of Hakkar"]               = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Zanza the Restless"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Zealot Lor'Khan"]             = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Zealot Zath"]                 = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Mad Voidwalker"]              = { mark = 4, creatureType = "Demon", dangerLevel = 2, note = "Warlock Banish target." },
        ["Razzashi Adder"]              = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Razzashi Cobra"]              = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Razzashi Raptor"]             = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Razzashi Serpent"]            = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Razzashi Venombrood"]         = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Zulian Guardian"]             = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Zulian Panther"]              = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Zulian Stalker"]              = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Zulian Tiger"]                = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Zulian Prowler"]              = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Bloodseeker Bat"]             = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Frog"]                        = "SKIP",
        ["Jungle Toad"]                 = "SKIP",
        ["Parasitic Serpent"]           = "SKIP",
        ["Snake"]                       = "SKIP",
        ["Spider"]                      = "SKIP",
        ["Toad"]                        = "SKIP",
    },

    ["Ruins of Ahn'Qiraj"] = {
        ["Anubisath Guardian"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Rolls a random ability set including Plague, Meteor and Explode; handle it by its mechanics and tank it away from the raid." },
        ["Anubisath Swarmguard"]        = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Anubisath Warder"]            = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Same random ability problem as the Guardians; check what it rolled before committing." },
        ["Colonel Zerran"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hive'Zara Hornet"]            = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Hive'Zara Stinger"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hive'Zara Soldier"]           = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Hive'Zara Wasp"]              = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Mana Fiend"]                  = { mark = 8, creatureType = "Demon", dangerLevel = 3, note = "Burns mana; kill it first in any pack where it appears." },
        ["Major Yeggeth"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Major Pakkon"]                = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Captain Drenn"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Captain Qeez"]                = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Captain Tuubid"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Captain Xurrem"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Obsidian Destroyer"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Drains mana and hits very hard; kill it before the casters are emptied." },
        ["Spitting Scarab"]             = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Swarmguard Needler"]          = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Beetle"]                      = "SKIP",
        ["Buru Egg"]                    = "SKIP",
        ["Canal Frenzy"]                = "SKIP",
        ["Hive'Zara Larva"]             = "SKIP",
        ["Scorpion"]                    = "SKIP",
        ["Silicate Feeder"]             = "SKIP",
        ["Qiraji Gladiator"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Hits unusually fast and hard; top priority in every pack it appears in." },
    },

    ["Temple of Ahn'Qiraj"] = {
        ["Anubisath Defender"]          = { note = "Handle Meteor, Plague, and Explode by their mechanics; defenders must be cleared before Twin Emperors, but no universal pack kill order is safe." },
        ["Anubisath Sentinel"]          = { note = "Ability rolls differ: kill the Sentinel with the least dangerous ability first because survivors heal and inherit the dead Sentinel's ability." },
        ["Eye Tentacle"]                = { mark = 8, creatureType = "Aberration", dangerLevel = 2, ccImmune = true },
        ["Giant Eye Tentacle"]          = { mark = 8, creatureType = "Aberration", dangerLevel = 2, ccImmune = true },
        ["Giant Claw Tentacle"]         = { mark = 8, creatureType = "Aberration", dangerLevel = 2, ccImmune = true },
        ["Qiraji Scarab"]               = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Obsidian Eradicator"]         = { note = "Pull/tank separately and interrupt or control its dangerous casts; exact order depends on the pack and raid plan." },
        ["Obsidian Nullifier"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 2 },
        ["Qiraji Brainwasher"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Mind Control and feared Mind Flay make this the first kill in packs with Vekniss Warriors." },
        ["Qiraji Mindslayer"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "In the pre-C'Thun Mindslayer packs, focus Mindslayers before Champions and Slayers." },
        ["Qiraji Champion"]             = { mark = 7, creatureType = "Humanoid", dangerLevel = 2, note = "Pre-C'Thun pack order: after Mindslayers and before Slayers." },
        ["Qiraji Slayer"]               = { note = "Pre-C'Thun three-target order places Slayers after Mindslayers and Champions; the addon has no third dedicated kill-order icon, so this remains informational." },
        ["Qiraji Swarmguard"]           = { mark = 7, creatureType = "Humanoid", dangerLevel = 2 },
        ["Qiraji Lasher"]              = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Whirlwind/knockback hazard; pull packs back. In Vekniss Wasp packs, usually kill the Lasher first." },
        ["Spawn of Fankriss"]           = { mark = 8, creatureType = "Beast", dangerLevel = 2 },
        ["Vekniss Drone"]               = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Vekniss Guardian"]            = { mark = 5, creatureType = "Humanoid", dangerLevel = 2 },
        ["Vekniss Hive Crawler"]        = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Vekniss Soldier"]             = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Vekniss Stinger"]             = { note = "In Vekniss Wasp packs, usually last after the Qiraji Lasher and Wasps; adjust to the actual pack. No third dedicated kill-order icon is assigned." },
        ["Vekniss Warrior"]             = { mark = 7, creatureType = "Beast", dangerLevel = 2, note = "Kill after the Brainwasher in paired packs; each Warrior death spawns a large group of Vekniss Borers." },
        ["Vekniss Borer"]               = { mark = 8, creatureType = "Beast", dangerLevel = 2, note = "Borers spawn in a large group when a Vekniss Warrior dies; switch/AoE them before they overwhelm the raid." },
        ["Vekniss Wasp"]                = { mark = 7, creatureType = "Beast", dangerLevel = 2, note = "In Wasp packs, the usual order is Qiraji Lasher, Wasps, then Stinger." },
        ["Beetle"]                      = "SKIP",
        ["Dark Blue Qiraji Battle Tank"]  = "SKIP",
        ["Gilded Scarab"]               = "SKIP",
        ["Glob of Viscidus"]            = "SKIP",
        ["Light Blue Qiraji Battle Tank"] = "SKIP",
        ["Light Green Qiraji Battle Tank"] = "SKIP",
        ["Orange Qiraji Battle Tank"]   = "SKIP",
        ["Scorpion"]                    = "SKIP",
        ["Twilight Qiraji Battle Tank"] = "SKIP",
    },

    ["Naxxramas"] = {
        ["Bile Retcher"]                = { mark = 7, creatureType = "Undead", dangerLevel = 2 },
        ["Soldier of the Frozen Wastes"] = { mark = 8, creatureType = "Undead", dangerLevel = 3, note = "Kel'Thuzad phase-one ranged priority: kill before it reaches anyone and triggers raid-wide Dark Blast." },
        ["Unstoppable Abomination"]     = { note = "Kel'Thuzad phase-one melee add; tank/manage its healing-reduction debuff. Assignment and wave position matter more than a universal kill order." },
        ["Deathknight Captain"]         = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Deathknight Cavalier"]        = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Eye Stalk"]                   = { mark = 8, creatureType = "Aberration", dangerLevel = 2, ccImmune = true },
        ["Mad Scientist"]               = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster and summoner; kill it early." },
        ["Living Poison"]               = "SKIP",
        ["Living Monstrosity"]          = { mark = 8, creatureType = "Aberration", dangerLevel = 2 },
        ["Naxxramas Acolyte"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Naxxramas Cultist"]           = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Caster; interrupt and kill first." },
        ["Naxxramas Follower"]          = { mark = 5, creatureType = "Humanoid", dangerLevel = 1 },
        ["Necro Knight"]                = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Necro Stalker"]               = { mark = 5, creatureType = "Aberration", dangerLevel = 2 },
        ["Necropolis Acolyte"]          = { mark = 8, creatureType = "Humanoid", dangerLevel = 3, note = "Healer; interrupt and kill first." },
        ["Shade of Naxxramas"]          = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Skeletal Smith"]              = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Soul Weaver"]                 = { mark = 7, creatureType = "Undead", dangerLevel = 3, note = "Kel'Thuzad phase-one wave add; ranged players kill it and Soldiers before they reach the raid." },
        ["Spectral Deathknight"]        = { note = "Gothik dead-side wave: use the side-specific kill/CC order; it differs from the living side." },
        ["Spectral Horseman"]           = { note = "Gothik dead-side wave: horsemen are handled after the other assigned adds; follow the side-specific plan." },
        ["Spectral Rider"]              = { note = "Gothik dead-side wave: follow the side-specific kill order; live-side Riders are a higher priority." },
        ["Spectral Trainee"]            = { note = "Gothik dead-side wave: follow the side-specific order; do not apply the living-side priority here." },
        ["Spirit of Naxxramas"]         = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Stoneskin Gargoyle"]          = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Surgical Assistant"]          = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Unholy Staff"]                = { mark = 8, creatureType = "Undead", dangerLevel = 2 },
        ["Unrelenting Deathknight"]     = { note = "Gothik living-side Death Knights can be Shackled; wave-side and raid composition determine whether to CC or kill." },
        ["Unrelenting Rider"]           = { note = "Gothik living-side Riders are a high priority; the dead-side order differs, so no global fixed mark is enforced." },
        ["Unrelenting Trainee"]         = { note = "Gothik living-side Trainees are lowest priority; the dead-side order starts differently. Follow the wave/side plan." },
        ["Carrion Spinner"]             = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Dread Creeper"]               = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Frenzied Bat"]                = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Infectious Skitterer"]        = { mark = 5, creatureType = "Beast", dangerLevel = 2 },
        ["Plagued Bat"]                 = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Plagued Deathhound"]          = { mark = 5, creatureType = "Beast", dangerLevel = 1 },
        ["Venom Stalker"]               = { mark = 5, creatureType = "Aberration", dangerLevel = 2 },
        ["Bile Sludge"]                 = "SKIP",
        ["Corpse Scarab"]               = "SKIP",
        ["Larva"]                       = "SKIP",
        ["Maggot"]                      = "SKIP",
        ["Plague Slime"]                = "SKIP",
        ["Rat"]                         = "SKIP",
        ["Spider"]                      = "SKIP",
        ["Spore"]                       = "SKIP",
        ["Web Wrap"]                    = "SKIP",
    },
}

-- Merge Classic data into the runtime lookup without replacing any entries
-- supplied by an earlier module. Keep AutoMarkAssist_MobDB as a compatibility alias.
PsychoMarksYou_DefaultMobs = PsychoMarksYou_DefaultMobs or {}
for zone, mobs in pairs(AutoMarkAssist_MobDB) do
    local runtimeZone = PsychoMarksYou_DefaultMobs[zone]
    if not runtimeZone then
        runtimeZone = {}
        PsychoMarksYou_DefaultMobs[zone] = runtimeZone
    end
    for mobName, entry in pairs(mobs) do
        if runtimeZone[mobName] == nil then
            runtimeZone[mobName] = entry
        end
    end
end

-- ============================================================
-- ZONE ALIASES
-- Maps alternate / partial zone name strings to canonical DB keys.
-- Subsequent expansion modules merge into this table.
-- ============================================================

PsychoMarksYou_ZoneAliases = {
    ["Ragefire Chasm"]                  = "Ragefire Chasm",
    ["Ragefire"]                        = "Ragefire Chasm",
    ["Wailing Caverns"]                 = "Wailing Caverns",
    ["Deadmines"]                       = "The Deadmines",
    ["The Deadmines"]                   = "The Deadmines",
    ["Shadowfang Keep"]                 = "Shadowfang Keep",
    ["Shadowfang"]                      = "Shadowfang Keep",
    ["The Stockade"]                    = "The Stockade",
    ["Stockade"]                        = "The Stockade",
    ["Stormwind Stockade"]              = "The Stockade",
    ["Blackfathom Deeps"]               = "Blackfathom Deeps",
    ["Blackfathom"]                     = "Blackfathom Deeps",
    ["Gnomeregan"]                      = "Gnomeregan",
    ["Razorfen Kraul"]                  = "Razorfen Kraul",
    ["Razorfen Downs"]                  = "Razorfen Downs",
    ["Scarlet Halls"]                   = "Scarlet Halls",
    ["Scarlet Monastery"]               = "Scarlet Monastery",
    ["Scarlet Monastery: Graveyard"]    = "Scarlet Monastery",
    ["Scarlet Monastery: Library"]      = "Scarlet Monastery",
    ["Scarlet Monastery: Armory"]       = "Scarlet Monastery",
    ["Scarlet Monastery: Cathedral"]    = "Scarlet Monastery",
    ["Scarlet Monastery Graveyard"]     = "Scarlet Monastery",
    ["Scarlet Monastery Library"]       = "Scarlet Monastery",
    ["Scarlet Monastery Armory"]        = "Scarlet Monastery",
    ["Scarlet Monastery Cathedral"]     = "Scarlet Monastery",
    ["Uldaman"]                         = "Uldaman",
    ["Zul'Farrak"]                      = "Zul'Farrak",
    ["Maraudon"]                        = "Maraudon",
    ["Maraudon: Wicked Grotto"]         = "Maraudon",
    ["Maraudon: Foulspore Cavern"]      = "Maraudon",
    ["Maraudon: Earth Song Falls"]      = "Maraudon",
    ["Dire Maul"]                       = "Dire Maul",
    ["Dire Maul East"]                  = "Dire Maul",
    ["Dire Maul West"]                  = "Dire Maul",
    ["Dire Maul North"]                 = "Dire Maul",
    ["Dire Maul: Warpwood Quarter"]     = "Dire Maul",
    ["Dire Maul: Capital Gardens"]      = "Dire Maul",
    ["Dire Maul: Gordok Commons"]       = "Dire Maul",
    ["Stratholme"]                      = "Stratholme",
    ["Stratholme Main Gate"]            = "Stratholme",
    ["Stratholme Service Gate"]         = "Stratholme",
    ["Stratholme: Live"]                = "Stratholme",
    ["Stratholme: Dead"]                = "Stratholme",
    ["Scholomance"]                     = "Scholomance",
    ["Temple of Atal'Hakkar"]           = "The Temple of Atal'Hakkar",
    ["The Temple of Atal'Hakkar"]       = "The Temple of Atal'Hakkar",
    ["Sunken Temple"]                   = "The Temple of Atal'Hakkar",
    ["Blackrock Depths"]                = "Blackrock Depths",
    ["Lower Blackrock Spire"]           = "Lower Blackrock Spire",
    ["Blackrock Spire: Lower"]          = "Lower Blackrock Spire",
    ["LBRS"]                            = "Lower Blackrock Spire",
    ["Upper Blackrock Spire"]           = "Upper Blackrock Spire",
    ["Blackrock Spire: Upper"]          = "Upper Blackrock Spire",
    ["Blackrock Spire"]                 = "Upper Blackrock Spire",
    ["BRS Upper"]                       = "Upper Blackrock Spire",
    ["UBRS"]                            = "Upper Blackrock Spire",
    ["Molten Core"]                     = "Molten Core",
    ["MC"]                              = "Molten Core",
    ["Onyxia's Lair"]                   = "Onyxia's Lair",
    ["Onyxias Lair"]                    = "Onyxia's Lair",
    ["Onyxia"]                          = "Onyxia's Lair",
    ["Ony"]                             = "Onyxia's Lair",
    ["Blackwing Lair"]                  = "Blackwing Lair",
    ["Blackwing"]                       = "Blackwing Lair",
    ["BWL"]                             = "Blackwing Lair",
    ["Zul'Gurub"]                       = "Zul'Gurub",
    ["ZG"]                              = "Zul'Gurub",
    ["Ruins of Ahn'Qiraj"]              = "Ruins of Ahn'Qiraj",
    ["Ruins of AhnQiraj"]               = "Ruins of Ahn'Qiraj",
    ["AQ20"]                            = "Ruins of Ahn'Qiraj",
    ["AQ 20"]                           = "Ruins of Ahn'Qiraj",
    ["Temple of Ahn'Qiraj"]             = "Temple of Ahn'Qiraj",
    ["Temple of AhnQiraj"]              = "Temple of Ahn'Qiraj",
    ["AQ40"]                            = "Temple of Ahn'Qiraj",
    ["AQ 40"]                           = "Temple of Ahn'Qiraj",
    ["Naxxramas"]                       = "Naxxramas",
    ["Naxx"]                            = "Naxxramas",
}

-- ============================================================
-- EXPANSION ORDER
-- Defines the display order for the Database tab zone grouping.
-- Subsequent expansion modules append to this table.
-- ============================================================

PsychoMarksYou_ExpansionOrder = {
    { name = "Classic", dungeons = {
        "Ragefire Chasm", "Wailing Caverns", "The Deadmines", "Shadowfang Keep",
        "The Stockade", "Blackfathom Deeps", "Gnomeregan", "Razorfen Kraul",
        "Razorfen Downs", "Scarlet Halls", "Scarlet Monastery", "Uldaman", "Zul'Farrak",
        "Maraudon", "Dire Maul", "Stratholme", "Scholomance",
        "The Temple of Atal'Hakkar", "Blackrock Depths", "Lower Blackrock Spire",
        "Upper Blackrock Spire",
    }, raids = {
        "Molten Core", "Onyxia's Lair", "Blackwing Lair", "Zul'Gurub",
        "Ruins of Ahn'Qiraj", "Temple of Ahn'Qiraj", "Naxxramas",
    }},
}
